CREATE DATABASE COVID_19 ;

USE COVID_19 ;

SELECT * FROM Covid_19_data ;

--GETTING ALL THE COLUMN NAMES PRESENT IN THE DATASET :

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Covid_19_data' ;

--TOTAL NUMBER OF RECORDS IN THE DATASET

SELECT 
   COUNT(*) AS
   Total_records
FROM 
   COVID_19_DATA
   ;



--NUMBER OF UNIQUE REGION

SELECT 
    COUNT(DISTINCT REGION)
	AS Total_regions 
FROM 
    COVID_19_DATA
	;


--FILTERING THE DATA BY STATE OR REGION :

SELECT 
     *
FROM 
    COVID_19_DATA
WHERE 
    STATE = 'hunan' ;


--SORTING DATA BY CONFIRMED CASE :

SELECT
     *
FROM  
     COVID_19_DATA
ORDER BY 
     CONFIRMED DESC ;


--FILTERING DATA BY CONFIRMED CASES GREATER THAN THRESHOLD :

SELECT * 
FROM COVID_19_DATA
WHERE CONFIRMED > 50000 ;


--COUNT THE TOTAL NUMBER OF CONFIRMED CASES :

SELECT 
     SUM(CONFIRMED)  AS
	 'TOTAL CONFIRMED CASES'
FROM
     COVID_19_DATA ;



--FIND TOTAL CONFIRMED CASES PER STATE :

SELECT 
     STATE,
	 SUM(CONFIRMED)AS
	 CONFIRMED_CASES
FROM
     COVID_19_DATA
GROUP BY
     STATE 
ORDER BY
     CONFIRMED_CASES
	 DESC;


SELECT * FROM COVID_19_DATA ;


--HOW MANY DEATHS IN EACH REGION :

SELECT 
     REGION,
	 COUNT(DEATHS)AS 
	 TOTAL_DEATHS
FROM
    COVID_19_DATA 
GROUP BY 
    REGION 
ORDER BY
    TOTAL_DEATHS DESC ;


--FIND THE STATE WHERE THERE IS NO DEATH :

SELECT 
    STATE,
	DEATHS
FROM
    COVID_19_DATA
WHERE
    DEATHS = 0 ;


--WHAT IS THE AVERAGE RECOVERED CASES IN EVERY STATE ?

SELECT 
     STATE,
	 AVG(RECOVERED) AS
	 AVG_R_CASES
FROM 
     COVID_19_DATA 
GROUP BY
     STATE
ORDER BY
     AVG_R_CASES DESC ;


--IN WHICH REGION DEATHS ARE MORE THAN THE THRESHOLD LIMIT THAT IS 1000 ?

SELECT 
     REGION,
	 STATE,
	 SUM(DEATHS) AS 
	 TOTAL_DEATHS
FROM
     COVID_19_DATA
GROUP BY
     REGION,
	 STATE
HAVING 
     SUM(DEATHS) > 1000
ORDER BY
     SUM(DEATHS) DESC ;


--PERCENTAGE OF RECOVERED CASES :

SELECT
     ROUND(SUM(RECOVERED) * 100.0 /
	 SUM(CONFIRMED),2)   AS 
	 'RECOVERY RATE'
FROM
    COVID_19_DATA


-- WHAT IS TH E PERCENATGE OF DEATHS :

SELECT 
      ROUND(SUM(DEATHS) * 100.0 / 
      SUM(CONFIRMED), 2) AS 
	  'Mortality Rate'
FROM 
     COVID_19_DATA;



--WHAT IS THE DIFFERENCE BETWEEN THE CONFIRMED CASES AND THE RECOVERED CASES ?

SELECT 
     STATE,
	 (CONFIRMED - RECOVERED)
	 AS ACTIVE_CASES
FROM
     COVID_19_DATA
ORDER BY
     ACTIVE_CASES DESC ;


--FIND THE 5 REGION WITH THE HIGHEST DEATH TO CONFIRMED CASE RATIO :

SELECT 
     TOP 5 
	 REGION,
	 SUM(DEATHS)AS 
	 TOTAL_DEATHS,
	 SUM(CONFIRMED)AS
	 TOTAL_CONFIRMED,
	 ROUND(SUM(DEATHS)*100.0 /
	 SUM(CONFIRMED),2) AS DEATH_RATE
FROM
     COVID_19_DATA
GROUP BY
     REGION
ORDER BY
     DEATH_RATE DESC ;


-- RANK EVERY STATE BY RECOVERY RATE :

SELECT
     STATE,
	 ROUND(SUM(RECOVERED)*100.0 / 
	 SUM(CONFIRMED),2) AS RECOVERY_RATE ,
	 RANK() OVER(ORDER BY ROUND(SUM(RECOVERED)*100.0 /
	 SUM(CONFIRMED),2)DESC) AS RANK
FROM
     COVID_19_DATA
GROUP BY
     STATE ;


SELECT * FROM COVID_19_DATA ;


--WHAT ARE THE TOTAL ACTIVE CASES PER REGION :

SELECT 
     REGION,
	 SUM(CONFIRMED - RECOVERED - DEATHS) AS
	 ACTIVE_CASES
FROM
     COVID_19_DATA
GROUP BY
     REGION
ORDER BY
     ACTIVE_CASES DESC;


