USE APARNA ;

-- TO DISPLAY ALL THE RECORDS 
SELECT * FROM
BIKE_SALES_INDIA ;

--TO GET THE COLUMNS NAME 
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'BIKE_SALES_INDIA'


--LIST ALL THE DISTINCT BRANDS OF BIKES

SELECT
    DISTINCT(BRAND)
	 AS UNIQUE_BRAND
FROM
    BIKE_SALES_INDIA ;


--FIND THE TOTAL NUMBER OF BIKES LISTED FOR SALE:

SELECT 
     COUNT(*) AS 
	 "NUMBER OF BIKES"
FROM
     BIKE_SALES_INDIA ;


--SHOW THE AVERAGE RESALE PRICE OF BIKES BY BRAND :

SELECT 
      BRAND
	 ,AVG(RESALE_PRICE_INR)
	 AS AVG_RESALE_PRICE
FROM
     BIKE_SALES_INDIA
GROUP BY
     BRAND ;



SELECT * FROM
     BIKE_SALES_INDIA;


--RETRIEVE THE DETAILS OF BIKES MANUFACTURED AFTER 2015;

SELECT * FROM
    BIKE_SALES_INDIA 
WHERE
   YEAR_OF_MANUFACTURE > 2015
   ;

--DISPLAY THE COUNT OF BIKE BY FUEL TYPE :

SELECT 
     FUEL_TYPE
	,COUNT(*) 
	AS 'COUNT'
FROM
    BIKE_SALES_INDIA
GROUP BY
    FUEL_TYPE 
	;

--FIND THE HIGHEST RESALE PRICE OF BIKES 

SELECT 
     MAX(RESALE_PRICE_INR)
	 AS 'HIGHEST RESALE PRICE'
FROM
     BIKE_SALES_INDIA 
	 ;


--LIST THE AVERAGE MILEAGE FOR BIKES BY BRAND AND MODEL :

SELECT 
     BRAND
	,MODEL
	,AVG(MILEAGE_KM_l)
	AS 'AVERAGE MILEAGE'
FROM
    BIKE_SALES_INDIA 
GROUP BY 
     BRAND
	,MODEL
   ;

--FIND ALL THE BIKE WITH THE PRICE GREATER THAN INR 1,00,000:

SELECT 
      *
FROM
    BIKE_SALES_INDIA
WHERE
    PRICE_INR > 100000 
	;

--DISPLAY ALL THE BIKES THAT ARE FIRST TIME OWNER TYPE :

SELECT 
      *
FROM
    BIKE_SALES_INDIA
WHERE
    OWNER_TYPE = 'FIRST'
	;

--FIND THE NUMBER OF BIKES AVAILABLE BY CITY TIER:

SELECT 
      CITY_TIER
	 ,COUNT(*) AS
	 'COUNT'
FROM
     BIKE_SALES_INDIA
GROUP BY
     CITY_TIER
ORDER BY 
     COUNT(*) DESC 
	 ;

--LIST THE AVERAGE DAILY DISTANCE COVERED BY BIKES BY FUEL TYPE 

SELECT 
     FUEL_TYPE
    ,AVG(AVG_DAILY_DISTANCE_KM)
	 AS 'AVERAGE DISTANCE'
FROM
    BIKE_SALES_INDIA
GROUP BY 
    FUEL_TYPE
	;

--RETRIEVE THE OLDEST AND THE NEWEST BIKE MODEL AVAILABLE :

SELECT 
      MIN(YEAR_OF_MANUFACTURE)
	  AS 'OLDEST MODEL'
	 ,MAX(YEAR_OF_MANUFACTURE)
	  AS 'NEWEST MODEL'
FROM
    BIKE_SALES_INDIA
	;

--FIND THE RESALE PRICE DIFFERENCE BETWEEN BIKES WITH AND WITHOUT INSURANCE :

SELECT
     INSURANCE_STATUS
    ,AVG(RESALE_PRICE_INR)
	AS 'AVGERAGE RESALE PRICE'
FROM
   BIKE_SALES_INDIA
GROUP BY 
   INSURANCE_STATUS
   ;

SELECT 
  ABS(
    MAX(CASE WHEN Insurance_Status = 'ACTIVE' THEN Resale_Price_INR ELSE 0 END) -
    MAX(CASE WHEN Insurance_Status = 'EXPIRED' THEN Resale_Price_INR ELSE 0 END)
  ) AS Resale_Price_Difference
FROM 
  BIKE_SALES_INDIA;




-- FIND THE TOP 5 MOST EXPENSIVE BIKE BRANDS ON AVERAGE RESALE PRICE :

SELECT 
     TOP 5 BRAND
	,AVG(RESALE_PRICE_INR)
	AS AVG_RESALE_PRICE
FROM
    BIKE_SALES_INDIA 
GROUP BY
    BRAND
ORDER BY
    AVG_RESALE_PRICE DESC
	;

--LIST THE TOTAL NUMBER OF BIKES SOLD BY SELLER TYPE :

SELECT 
     SELLER_TYPE
	 ,COUNT(*) AS
	 'NUMBER OF BIKESOLD'
FROM 
     BIKE_SALES_INDIA
GROUP BY 
     SELLER_TYPE
	 ;


--FIND THE AVERAGE ENGINE CAPACITY OF BIKES IN EACH CITY TIER :

SELECT 
     CITY_TIER
	,AVG(ENGINE_CAPACITY_CC)
	AS 'AVERAGE ENGINE CAPACITY'
FROM
     BIKE_SALES_INDIA
GROUP BY
     CITY_TIER 
	 ;

--SHOW THE BIKES WITH THE HIGHEST MILEAGE PER LITRE FOR EACH BRAND:

SELECT 
      BRAND
	 ,MAX(MILEAGE_KM_l)
	 AS 'HIGHEST MILEAGE'
FROM
     BIKE_SALES_INDIA
GROUP BY
     BRAND 
	 ;

	 0R
SELECT 
     BRAND
	,MILEAGE_KM_l
FROM
    BIKE_SALES_INDIA
WHERE
    BRAND IN (
	           SELECT 
			        BRAND
				    ,MAX(MILEAGE_KM_l)
			   FROM
			       BIKE_SALES_INDIA
				GROUP BY
				    BRAND
		);
    

--FIND THE MOST COMMON REGISTRATION YEAR FOR BIKES :

SELECT 
     TOP 1
	 REGISTRATION_YEAR
     ,COUNT(*)
	 AS TOTAL_BIKES
FROM 
     BIKE_SALES_INDIA
GROUP BY
     REGISTRATION_YEAR
ORDER BY
     TOTAL_BIKES DESC
	 ;


SELECT * FROM 
     BIKE_SALES_INDIA

--RETRIEVE BIKE THAT HAVE A REGISTRATION YEAR EARLIER THAN THIER YEAR OF MANUFACTURE :

SELECT * FROM  BIKE_SALES_INDIA 
WHERE REGISTRATION_YEAR < YEAR_OF_MANUFACTURE
 ;

 --FIND THE DIFFERENCE BETWEEN THE ORIGINAL PRICE AND RESALE PRICE OF BIKES BY BRAND AND MODEL :

 SELECT 
      BRAND
	  ,MODEL
	  ,(PRICE_INR - RESALE_PRICE_INR)
	 AS 'DIFFERENCE BETWEEN PRICES'
FROM
     BIKE_SALES_INDIA 
	;


--CALCULATE THE AVERAGE RESALE PRICE OF BIKES GROUPED BY CITY TIER AND OWNER TYPE :

SELECT
     CITY_TIER
	,OWNER_TYPE
	,AVG(RESALE_PRICE_INR)
	AS 'AVERAGE RESALE PRICE'
FROM
     BIKE_SALES_INDIA
GROUP BY
     CITY_TIER
	,OWNER_TYPE
;


--FIND THE TOTAL RESALE PRICE OF BIKES SOLD BY FUEL TYPE IN EACH STATE:

SELECT 
     FUEL_TYPE
	 ,STATE
	 ,SUM(RESALE_PRICE_INR)
	 AS 'TOTAL RESALE PRICE'
FROM
     BIKE_SALES_INDIA
GROUP BY
     STATE
	 ,FUEL_TYPE
;


SELECT * FROM 
     BIKE_SALES_INDIA


--RETRIEVE THE PERCENTAGE OF BIKES WITH INSURANCE VS WITHOUT INSURANCE :

SELECT 
     Insurance_Status
	,COUNT(*) * 100.0 
	     /    (
				SELECT
					 COUNT(*)
				FROM
					bike_sales_india
		)AS 'PERCENTAGE'
FROM
    bike_sales_india
GROUP BY
    Insurance_Status


--SHOW THE BIKES THAT HAVE BEEN LISTED FOR RESALE MORE THAN ONCE BY SAME OWNER TYPE:

SELECT 
     BRAND
	 ,MODEL
	 ,Owner_Type
	 ,COUNT(*) AS 
	 'LISTING COUNT'
FROM
     bike_sales_india
GROUP BY
      Owner_Type
	  ,Brand
	  ,Model
HAVING 
     COUNT(*) > 1
	 ;



--FIND THE AVERAGE PRICE OF BIKES BASED ON ENGINE CAPACITY AND MILEAGE PER LITER :

SELECT
     Engine_Capacity_cc
	 ,Mileage_km_l
	 ,AVG(PRICE_INR) AS
	 'AVERAGE PRICE OF BIKES'
FROM
     bike_sales_india
GROUP BY
     Engine_Capacity_cc
	 ,Mileage_km_l


--CALCULATE THE TOTAL RESALE PRICE OF BIKES BY BRAND AND CITY TIER:

SELECT 
      Brand
	  ,City_Tier
	  ,SUM(Resale_Price_INR)
	  AS 'TOTAL RESALE PRICE'
FROM
     bike_sales_india
GROUP BY
      Brand
	  ,City_Tier
	;

    
	
--SHOW THE TOP 3 STATES WITH THE HIGHEST AVERAGE RESALE PRICE OF BIKES :

SELECT
      TOP 3 State
	  ,AVG(RESALE_PRICE_INR)
	  AS 'AVERAGE RESALE PRICE'
FROM
     bike_sales_india
GROUP BY
     State
ORDER BY
     'AVERAGE RESALE PRICE'
	;


/* IDENTIFY THE BIKES THAT COVER AN AVERAGE DAILY DISTANCE GREATER THAN 50 KM WITH A 
 RESALE PRICE UNDER INR 50,000. */

 SELECT 
      *
FROM
    bike_sales_india
WHERE
    Avg_Daily_Distance_km > 50
	AND Resale_Price_INR < 50000
;


-- FIND THE RANK OF BIKES BASED ON THIER RESALE PRICE WITHIN EACH FUEL TYPE :

SELECT
     Brand
	 ,Model
	 ,Resale_Price_INR
	 ,Fuel_Type
	 ,RANK() OVER(PARTITION BY FUEL_TYPE
	 ORDER BY RESALE_PRICE_INR DESC )
	 AS PRICE_RANK
FROM
    bike_sales_india
	;


/* SHOW THE DISTRIBUTION OF BIKES BASED ON ENGINE CAPACITY AND FUEL TYPE ,GROUPED BY 
PRICE RANGE (BELOW INR 50K ,50K-1L,ABOVE 1L) */

SELECT
      Engine_Capacity_cc
	  ,Fuel_Type
	  ,CASE
	       WHEN Price_INR < 50000 THEN 'BELOW 50K'
		   WHEN Price_INR BETWEEN 50000 AND 100000 THEN '50K - 1L'
		   ELSE 'ABOVE 1L'
	   END AS PRICE_RANGE
	  ,COUNT(*) AS TOTAL_BIKES
FROM
     bike_sales_india
GROUP BY
     Engine_Capacity_cc
	,Fuel_Type
	--,PRICE_RANGE ( CANT DO LIKE THIS SQL DOESNOT ALLOW)
	,CASE
	       WHEN Price_INR < 50000 THEN 'BELOW 50K'
		   WHEN Price_INR BETWEEN 50000 AND 100000 THEN '50K - 1L'
		   ELSE 'ABOVE 1L'
	 END
ORDER BY
     PRICE_RANGE DESC
	 ,TOTAL_BIKES DESC
;


--CALCULATE THE CUMULATIVE SUM OF RESALE PRICE FOR EACH BRAND,ORDERED BY RESALE PRICE:

SELECT 
     Brand
	 ,Model
	 ,SUM(RESALE_PRICE_INR)
	 OVER(PARTITION BY BRAND 
	 ORDER BY RESALE_PRICE_INR)
	 AS 'CUMULATIVE SUM OF RESALE PRICE'
FROM
    bike_sales_india
;

--FIND THE BIKES THAT HAVE A RESALE PRICE HIGHER THAN THE AVERAGE RESALE PRICE OF ALL BIKES :

SELECT 
      *
FROM
    bike_sales_india
WHERE 
    Resale_Price_INR >
	          (
			    SELECT
				     AVG(RESALE_PRICE_INR)
				FROM
				    bike_sales_india
			);


/* DISPLAY THE BRANDS AND MODELS WHERE THE RESALE PRICE IS GREATER THAN 
THE HIGHEST RESALE PRICE IN CITY_TEIR2 */

SELECT
     Brand
	 ,Model
	 ,Resale_Price_INR
FROM
    bike_sales_india
WHERE
    Resale_Price_INR >
	       (
		     SELECT
			      MAX(RESALE_PRICE_INR)
			 FROM 
			    bike_sales_india
			 WHERE City_Tier = 'TIER 2'
		)
	;


--CREATE A VIEW THAT SHOWS THE AVERAGE RESALE PRICE AND MILEAGE FOR EACH BIKE:

CREATE VIEW
     AVG_RESALEPRICE_MILEAGE_VIIEW AS
	   SELECT 
	        Brand
			,Model
			,AVG(RESALE_PRICE_INR)
			AS 'AVERAGE RESALE PRICE'
			,AVG(MILEAGE_KM_l) AS
			'AVERAGE MILEAGE'
	   FROM
	       bike_sales_india
       GROUP BY
	        Brand
			,Model
	;

--USING THE CREATED VIEW 

SELECT * FROM
AVG_RESALEPRICE_MILEAGE_VIIEW ;

SELECT * FROM
AVG_RESALEPRICE_MILEAGE_VIIEW
WHERE Brand = 'KTM';


/*CREATE A CTE THAT CALCULATES THE AVERAGE MILEAGE PER FUEL TYPE ,AND 
USE IT TO FIND BIKES WITH MILEAGE ABOVE THE AVERAGE FOR THIER FUEL TYPE */

WITH AVG_MILEAGE_PER_FUEL_TYPE AS (
            SELECT 
			      Fuel_Type
				  ,ROUND(AVG(MILEAGE_KM_l),3)
				  AS AVGERAGE_MILEAGE
			FROM
			    bike_sales_india
			GROUP BY
			      Fuel_Type
		) --A CTE cannot exist independently—We need a subsequent query to work.

SELECT 
      BS.Brand
	  ,BS.Model
	  ,BS.Mileage_km_l
	  ,AMPF.AVGERAGE_MILEAGE
FROM
    bike_sales_india AS BS
JOIN
    AVG_MILEAGE_PER_FUEL_TYPE
	AS AMPF
ON
   BS.Fuel_Type = AMPF.Fuel_Type
WHERE
   BS.Mileage_km_l > AMPF.AVGERAGE_MILEAGE
;


/* CREATE A CTE THAT CALCULATES THE TOTAL NUMBER OF BIKES SOLD PER CITY TIER AND 
FILTERS CITY TIERS WITH MORE THAN 1000 BIKES . */

WITH TOTAL_BIKES_PER_CITY_TIER AS (
             SELECT
			      CITY_TIER
				  ,COUNT(*) AS
				  'TOTAL_BIKES'
			 FROM
			     BIKE_SALES_INDIA
			 GROUP BY
			     CITY_TIER
		)

SELECT 
      *
FROM
    TOTAL_BIKES_PER_CITY_TIER
WHERE
    TOTAL_BIKES > 1000
;

--CALCULATE THE AVERAGE RESALE PRICE OF BIKES FOR EACH BRAND :

SELECT 
     BRAND
	 ,MODEL
	 ,Resale_Price_INR
     ,AVG(RESALE_PRICE_INR)
	 OVER (PARTITION BY BRAND
	 ORDER BY RESALE_PRICE_INR)
	 AS 'AVERAGE RESALE PRICE'
FROM
    bike_sales_india
;

--SHOW THE DIFFERENCE IN RESALE PRICE BETWEEN EACH BIKE AND THE PREVIOUS BIKE FOR EACH BRAND

SELECT
     BRAND
	 ,MODEL
	 ,RESALE_PRICE_INR
	 ,LAG(RESALE_PRICE_INR,1)
	 OVER(PARTITION BY BRAND
	 ORDER BY RESALE_PRICE_INR)
	 AS 'PREVIOUS BIKE PRICE'
FROM
    BIKE_SALES_INDIA
;


				  
    